### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by AgentBlackout** [sirmeepington/hasher#7]
# Description

In the README, the argument table, the line reads:

> -h | The has to compare the file hash against.

This does not make sense.

## Severity
Severity: Low
Impact: High
Remidiation priority: High

## Workaround

Squint eyes while skim-reading

## Solution

Fix typo

**Comment by sirmeepington** [comment]
Resolved as of https://github.com/sirmeepington/hasher/commit/6711276d634770548acf50fa8de0888ef8ae1d3b
